#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Regenerate src/domain/icons/catalog.scm from eza's icon table."""

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPOSITORY = "https://github.com/eza-community/eza"
TAG = "v0.23.5"
SOURCE = "src/output/icons.rs"
RAW = f"https://raw.githubusercontent.com/eza-community/eza/{TAG}/{SOURCE}"
TARGET = ROOT / "src" / "domain" / "icons" / "catalog.scm"

CONSTANT = re.compile(r"const\s+(\w+)\s*:\s*char\s*=\s*'\\u\{([0-9a-fA-F]+)\}'")
ENTRY = re.compile(
    r"""^\s*"((?:[^"\\]|\\.)*)"\s*=>\s*(?:Icons::(\w+)|'\\u\{([0-9a-fA-F]+)\}')\s*,"""
)
MAP = re.compile(r"const (\w+): Map<&'static str, char> = phf_map! \{")


def parse(text):
    constants = {name: chr(int(code, 16)) for name, code in CONSTANT.findall(text)}
    maps, current = {}, None
    for line in text.splitlines():
        opened = MAP.search(line)
        if opened:
            current = maps.setdefault(opened.group(1), {})
            continue
        if current is not None and line.startswith("};"):
            current = None
            continue
        if current is None:
            continue
        entry = ENTRY.match(line)
        if entry:
            key, name, code = entry.groups()
            current[key.encode().decode("unicode_escape")] = (
                constants[name] if name else chr(int(code, 16))
            )
    return constants, maps


def render(pairs):
    return "\n".join(
        f'    ({scheme(key)} {scheme(glyph)})' for key, glyph in sorted(pairs.items())
    )


def scheme(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main():
    with urllib.request.urlopen(RAW) as response:
        text = response.read().decode("utf-8")
    constants, maps = parse(text)
    fallbacks = {
        "file": constants["FILE"],
        "file-without-extension": constants["FILE_UNKNOW"],
        "directory": constants["FOLDER"],
        "expanded-directory": constants["FOLDER_OPEN"],
    }
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(
        f""";; Generated by tools/icons/generate.py. Do not edit.
;; Upstream: {REPOSITORY}
;; Tag: {TAG}
;; Source: {SOURCE}

(provide directory-entries filename-entries extension-entries fallback-entries)

(define directory-entries
  '(
{render(maps["DIRECTORY_ICONS"])}
  ))

(define filename-entries
  '(
{render(maps["FILENAME_ICONS"])}
  ))

(define extension-entries
  '(
{render(maps["EXTENSION_ICONS"])}
  ))

(define fallback-entries
  '(
{render(fallbacks)}
  ))
""",
        encoding="utf-8",
    )
    print(
        f"directories {len(maps['DIRECTORY_ICONS'])}, "
        f"filenames {len(maps['FILENAME_ICONS'])}, "
        f"extensions {len(maps['EXTENSION_ICONS'])}"
    )


if __name__ == "__main__":
    main()
